# These are supported funding model platforms

github: [Fabricio-P-Viana]
# patreon: # your patreon username
# open_collective: # your open collective username
# ko_fi: # your ko-fi username
# tidelift: # tidelift package name
# community_bridge: # your community bridge project name
# liberapay: # your liberapay username
# issuehunt: # your issuehunt username
# otechie: # your otechie username
# lfx_crowdfunding: # your LFX crowdfunding project name
# custom: # up to 4 custom sponsorship URLs
